- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
    check:
      jobs:
        - monasca-tempest-python-influxdb:
            voting: false
        - monasca-tempest-java-influxdb:
            voting: false
        - openstack-tox-lower-constraints
        - openstack-tox-cover
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - openstack-tox-cover
