- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
    check:
      jobs:
        - monasca-tempest-python2-influxdb:
            voting: false
        - monasca-tempest-python3-influxdb:
            voting: false
