- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - monasca-tempest-python-influxdb:
            voting: false
        - monasca-tempest-java-influxdb:
            voting: false
