- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-zed-jobs
    check:
      jobs:
        - monasca-tempest-python3-influxdb:
            voting: false
